name: instightful_interviews_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  build_runner: ^2.4.8
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  http: ^1.2.0
  image_picker: ^1.0.7
  mockito: ^5.4.4
  multi_select_flutter: ^4.1.3
  flutter_typeahead: ^5.2.0
  camera: ^0.10.5+9
  permission_handler: ^11.2.1
  record: ^4.4.4
  path_provider: ^2.1.2


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black-900.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold-800.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold-700.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold-600.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium-500.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular-400.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light-300.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-ExtraLight-200.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Thin-100.ttf
          weight: 100
